### ISSUE TITLE
fonctionalité d'import

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#25]
# Import

## Documentation

- [x] doc utilisateur pour l'import des passages faune
- ? doc technique exemple avancé
- [x] doc technique
  - [x] 2 étapes principale
    - [x] chargement et prétraitement
    - [x] insertion et mise à jour   
  - [x] exemple simple
    - [x] etape 1
    - [x] etape 2 insert / update   

## Frontend / Fonctionel

- composant fichier
    - [ ] ajouter contrainte sizemax
    - [ ] contrainte sur l'extention du fichier (.csv, ...)
- [ ] afficher le % de chargement du fichier
- [x] préciser le srid des données d'entrée
- [x] couleur boutton reset 
- [x] fin de l'import 
  - [x] lignes insérée
- [x] onglet erreur toujours visibile  
- [x] cacher les options
  - [x] boutton pour les afficher 
- [x] option x,y (ou automatique si geom null et x, y présents ??)
- [x] composant import dédié
- [x] layout utils.import
- [x] ajout d'une colonne `options` `JSONB` dans `gn_modulator.t_import`
  - [x] `insert_data` : insérer les données du csv avec un `INSERT` au lieu d'un `COPY`
  - [x] `enable_update`: si on autorise la modification de données
  - [x] `check_only`: 
    - charge, vérifie les données, crée les vues d'import et compte les insert et update
    - s'arrête avant l'insertion des données
- [x] ajout champs status:
  - [x] `PROCESSING`
  - [x]  `READY`
  - [x] `ERROR`
  - [x]  `DONE`
  - [ ] etc...
- [x] update non autorisé par défaut
- [x] import en deux étape
    - [x] verifier fichier, erreurs puis nb_action prévues (inser, update)
    - [x] valider et lancer les procédures d'insert et d'update
- [x] quand un import est effectué
    - afficher le résultat
    - recharger les données
    - proposer un nouvel import
- [x] composant import spécifique ou layout

## Droits
- [ ] dans les fonctions vérifier
  - [ ] `C`  pour insert
  - [ ] `U` pour update (filtre)
- [x] `I` pour ouvrir les action d'import
- [x] `C` pour le cruved  
- [x] frontend
- [] backend
  - [x] api

## Remontée erreurs
- [ ] si trop d'erreur proposer de télécharger les erreurs ?
- [ ] verification json schema, marshmallow ?

- [x] par ligne / ou type d'erreurs ?
- [x] champs obligatoires
- [x] fk non résolues
- [x] champs non valides (date, datetime, number, etc...)
- [x] champs uniques (pour clé primaire) présents

## sql, modeles

- [ ] fonction pour supprimer les tables de données et vues d'import pour les imports terminés
- [ ] renommer gn_modulator_import en gn_modulator_import_tmp
- [x] ajout meta_update_date, meta_create_date dans t_import
- ? deplacer t_import dans gn_modulator_import
- ? stocker les mapping en base ?

## backend
- [x] check options srid sql injection
- id_digitiser
    - [x] seulement pour l'insert
    - [ ] personalisable dans le schema
    - [ ] pouvoir le preciser pour l'import en cli
- update
    - [ ] filtrer selon `ownership` et CRUVED U si besoin
  - [ ] pouvoir garder la trace de toutes les instructions sql pour un import.
- data
    - ? gérer encodage
- [x] mapping
    - [x] blinder contre sql injction
        - [x] SELECT présent
        - [x] forbidden: ALTER CREATE GRANT, COPY
- [x] relations
    - [x] `count update` tester si une relation est modifiée
- [x] raw
    - ~utiliser NULLIF~
      - gestion des `NULL dans la table des données`

## test
  - [ ] remontée erreurs
    - [ ] ERR_IMPORT_REQUIRED
    - [ ] ERR_IMPORT_UNRESOLVED
    - [x] ERR_IMPORT_MISSING_UNIQUE
    - [x] ERR_IMPORT_INVALID_VALUE_FOR_TYPE
  - [ ] bug bizzare. `la colonne...n'est pas dans la table ...`
    - surveiller les id_import ?
    - résolu en supprimant le schema `gn_modulator_import`
    - [ ] ? remettre le serial à max id (si inférieur)? 
## les extra
  - ? celery
  - ? générer le sql avec sqlalchemy
  - ? relier features et import
  - ? ajouter entry_type à t_passages_faune
  - ? gérer des source différentes (geojson ,shapes etc..)
  - ? pouvoir tester les relation pour les update
    - array_agg(id_foreign order by id_foreign) ?? 
### optimisation
- ? check_type en une seule requête pour toutes les colonnes

**Comment by camillemonchicourt** [comment]
Une première version d'import est en cours de développement dans SIPAF.

Si l'utilisateur a des droits de création de donnés, il voit un bouton d'IMPORT : 

![image](https://user-images.githubusercontent.com/4418840/224352643-cb9d2f31-ac0b-41c6-afe2-a7e412150a83.png)

Une fenêtre d'import s'ouvre alors, proposant d'uploader le fichier : 

![image](https://user-images.githubusercontent.com/4418840/224352806-6e7bc9fb-c676-41de-b8af-df46b983edbe.png)

- Un format prédéfini de fichier sera fourni, avec un exemple et de la documentation.
- Le fichier importé devra correspondre au format de fichier attendu.
- Des colonnes seront obligatoires, et la plupart optionnelles
- Les valeurs attendues des champs seront aussi documentées
- Un acteur (organisme) par PAF pourra être renseigné dans le fichier à importer
- Le fichier devra obligatoirement comporter une géolocalisation du PAF (X et Y ou WKT)

Si le fichier importé est entièrement valide, une message de confirmation indiquant le nombre de données importées sera affiché (design en cours de développement) :

![image](https://user-images.githubusercontent.com/4418840/224353855-68a85d47-7527-45c0-ad6b-3263af9f31e8.png)

Si le fichier comporte des erreurs, des données déjà importées, des données incorrectes ou inconnu (comme un organisme non présent dans la BDD), l'erreur complet sera annulé, et un rapport listera les lignes problématiques et les erreurs correspondantes.

L'utilisateur pourra alors retravailler son fichier pour corriger ces erreurs et re-importer le fichier corrigé

**Comment by camillemonchicourt** [comment]
Première version réalisée dans https://github.com/PnX-SI/gn_modulator/pull/30
