### ISSUE TITLE
Installation du module Modulator qui ne marche pas

### ISSUE THREAD

**Issue by marineteneur** [PnX-SI/gn_modulator#39]
Bonjour,
Je souhaiterai créer un sous module dans Modulator avec un modèle de données bien précis.
Mais, l'installation du module ne marche pas pour moi (sur une version 2.12.3). Pourriez-vous m'aider ?

J'ai ces messages lors de l'installation avant qu'elle ne s'arrête :

Installation du backend…
Obtaining file:///home/geonatureadmin/gn_modulator
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting jsonschema (from gn-modulator==1.0.5)
  Downloading jsonschema-4.17.3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.4/90.4 kB 666.1 kB/s eta 0:00:00
Requirement already satisfied: utils-flask-sqlalchemy>=0.2.6 in ./geonature/backend/venv/lib/python3.7/site-packages (from gn-modulator==1.0.5) (0.3.3)
Collecting unidecode (from gn-modulator==1.0.5)
  Downloading Unidecode-1.3.6-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.9/235.9 kB 2.3 MB/s eta 0:00:00
Collecting py7zr (from gn-modulator==1.0.5)
  Downloading py7zr-0.20.5-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 1.0 MB/s eta 0:00:00
Collecting pyyaml (from gn-modulator==1.0.5)
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 596.3/596.3 kB 3.3 MB/s eta 0:00:00
Collecting sqlparse (from gn-modulator==1.0.5)
  Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 2.0 MB/s eta 0:00:00
Collecting py-mini-racer (from gn-modulator==1.0.5)
  Downloading py_mini_racer-0.6.0-py2.py3-none-manylinux1_x86_64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 5.1 MB/s eta 0:00:00
Requirement already satisfied: flask in ./geonature/backend/venv/lib/python3.7/site-packages (from utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (2.2.2)
Requirement already satisfied: flask-sqlalchemy in ./geonature/backend/venv/lib/python3.7/site-packages (from utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (2.5.1)
Requirement already satisfied: flask-migrate in ./geonature/backend/venv/lib/python3.7/site-packages (from utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (3.1.0)
Requirement already satisfied: marshmallow in ./geonature/backend/venv/lib/python3.7/site-packages (from utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (3.17.1)
Requirement already satisfied: python-dateutil in ./geonature/backend/venv/lib/python3.7/site-packages (from utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (2.8.2)
Requirement already satisfied: sqlalchemy<2,>=1.3 in ./geonature/backend/venv/lib/python3.7/site-packages (from utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (1.3.24)
Requirement already satisfied: attrs>=17.4.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from jsonschema->gn-modulator==1.0.5) (22.1.0)
Requirement already satisfied: importlib-metadata in ./geonature/backend/venv/lib/python3.7/site-packages (from jsonschema->gn-modulator==1.0.5) (4.12.0)
Requirement already satisfied: importlib-resources>=1.4.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from jsonschema->gn-modulator==1.0.5) (5.12.0)
Collecting pkgutil-resolve-name>=1.3.10 (from jsonschema->gn-modulator==1.0.5)
  Using cached pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 (from jsonschema->gn-modulator==1.0.5)
  Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in ./geonature/backend/venv/lib/python3.7/site-packages (from jsonschema->gn-modulator==1.0.5) (4.5.0)
Collecting texttable (from py7zr->gn-modulator==1.0.5)
  Downloading texttable-1.6.7-py2.py3-none-any.whl (10 kB)
Collecting pycryptodomex>=3.6.6 (from py7zr->gn-modulator==1.0.5)
  Downloading pycryptodomex-3.18.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 4.7 MB/s eta 0:00:00
Collecting pyzstd>=0.14.4 (from py7zr->gn-modulator==1.0.5)
  Downloading pyzstd-0.15.7-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (399 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 399.2/399.2 kB 3.1 MB/s eta 0:00:00
Collecting pyppmd<1.1.0,>=0.18.1 (from py7zr->gn-modulator==1.0.5)
  Downloading pyppmd-1.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.6/138.6 kB 5.4 MB/s eta 0:00:00
Collecting pybcj>=0.6.0 (from py7zr->gn-modulator==1.0.5)
  Downloading pybcj-1.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 13.5 MB/s eta 0:00:00
Collecting multivolumefile>=0.2.3 (from py7zr->gn-modulator==1.0.5)
  Downloading multivolumefile-0.2.3-py3-none-any.whl (17 kB)
Collecting brotli>=1.0.9 (from py7zr->gn-modulator==1.0.5)
  Using cached Brotli-1.0.9-cp37-cp37m-manylinux1_x86_64.whl (357 kB)
Collecting inflate64>=0.3.1 (from py7zr->gn-modulator==1.0.5)
  Downloading inflate64-0.3.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.6/93.6 kB 3.3 MB/s eta 0:00:00
Collecting psutil (from py7zr->gn-modulator==1.0.5)
  Downloading psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.1/282.1 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: zipp>=3.1.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from importlib-resources>=1.4.0->jsonschema->gn-modulator==1.0.5) (3.8.1)
Requirement already satisfied: Werkzeug>=2.2.2 in ./geonature/backend/venv/lib/python3.7/site-packages (from flask->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (2.2.2)
Requirement already satisfied: Jinja2>=3.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from flask->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from flask->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (2.1.2)
Requirement already satisfied: click>=8.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from flask->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (8.1.3)
Requirement already satisfied: alembic>=0.7 in ./geonature/backend/venv/lib/python3.7/site-packages (from flask-migrate->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (1.8.1)
Requirement already satisfied: packaging>=17.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from marshmallow->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (21.3)
Requirement already satisfied: six>=1.5 in ./geonature/backend/venv/lib/python3.7/site-packages (from python-dateutil->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (1.16.0)
Requirement already satisfied: Mako in ./geonature/backend/venv/lib/python3.7/site-packages (from alembic>=0.7->flask-migrate->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (1.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./geonature/backend/venv/lib/python3.7/site-packages (from Jinja2>=3.0->flask->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (2.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./geonature/backend/venv/lib/python3.7/site-packages (from packaging>=17.0->marshmallow->utils-flask-sqlalchemy>=0.2.6->gn-modulator==1.0.5) (3.0.9)
Building wheels for collected packages: gn-modulator
  Building editable for gn-modulator (pyproject.toml) ... done
  Created wheel for gn-modulator: filename=gn_modulator-1.0.5-0.editable-py3-none-any.whl size=15351 sha256=3a17568c618389c5cdd8e38d5e08c046a7fca8a38e93034a54ffb560eda5cc75
  Stored in directory: /tmp/pip-ephem-wheel-cache-rke3v_4g/wheels/bf/48/8a/f569ede90b6b8500aefd2ed8e17046e26d256887d820b59137
Successfully built gn-modulator
Installing collected packages: texttable, py-mini-racer, brotli, unidecode, sqlparse, pyzstd, pyyaml, pyrsistent, pyppmd, pycryptodomex, psutil, pkgutil-resolve-name, multivolumefile, pybcj, jsonschema, inflate64, py7zr, gn-modulator
Successfully installed brotli-1.0.9 gn-modulator-1.0.5 inflate64-0.3.1 jsonschema-4.17.3 multivolumefile-0.2.3 pkgutil-resolve-name-1.3.10 psutil-5.9.5 py-mini-racer-0.6.0 py7zr-0.20.5 pybcj-1.0.1 pycryptodomex-3.18.0 pyppmd-1.0.0 pyrsistent-0.19.3 pyyaml-6.0 pyzstd-0.15.7 sqlparse-0.4.4 texttable-1.6.7 unidecode-1.3.6
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 38, in install_gn_module
    importlib.reload(geonature.utils.config)
  File "/usr/lib/python3.7/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/geonatureadmin/geonature/backend/geonature/utils/config.py", line 35, in <module>
    config_frontend = GnGeneralSchemaConf().load(config_toml, unknown=EXCLUDE)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 902, in _do_load
    partial=partial,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1101, in _invoke_load_processors
    partial=partial,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1225, in _invoke_processors
    data = processor(data, many=many, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/config_schema.py", line 586, in insert_module_config
    module_code = dist.entry_points["code"].load()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/geonatureadmin/gn_modulator/backend/gn_modulator/__init__.py", line 4, in <module>
    from .definition import DefinitionMethods
  File "/home/geonatureadmin/gn_modulator/backend/gn_modulator/definition/__init__.py", line 1, in <module>
    from .base import DefinitionBase
  File "/home/geonatureadmin/gn_modulator/backend/gn_modulator/definition/base.py", line 395
    if dependencies := definition_type not in [
                     ^
SyntaxError: invalid syntax

**Comment by joelclems** [comment]
```
if dependencies := definition_type not in
```

C'est une syntaxe qui est valide à partir de python 3.8.

**Comment by camillemonchicourt** [comment]
Bonjour,

Ce module est encore très jeune.
Utilisé uniquement pour l'inventaire national des Passages à faune, en test/démo ici : https://outils.cevennes-parcnational.net/demo-sipaf/geonature/#/modulator/m_sipaf (admin / admin).
Comme indiqué dans les notes de version, la version 1.0 du module est compatible avec la version 2.11 de GeoNature.
La compatibilité avec GeoNature 2.12 est en cours dans la branche de développement, mais pas encore sortie sous forme de version officielle.

Pour la compatibilité GeoNature, cela pourrait être mentionné dans le fichier `requirements.in`, comme sur d'autres modules (https://github.com/PnX-SI/gn_module_import/blob/master/requirements.in#L6)

@joelclems concernant ton retour, cela veut dire que le module nécessite python 3.8 minimum, donc non compatible avec une version minimum de Debian ?
C'est possible de corriger ça ou il faut indiquer une version minimum de Python (et donc Debian ?)

**Comment by joelclems** [comment]
C'est déjà fait mais pour la prochaine release

**Comment by camillemonchicourt** [comment]
Bonjour,
Il y a en effet pas mal de développements en cours, en vue de sortir une nouvelle version compatible avec GeoNature 2.12.
Liste des développements en question : https://github.com/PnX-SI/gn_modulator/compare/develop

Vous pouvez tester ces développements compatibles avec GeoNature 2.12, en installant la branche DEVELOP : https://github.com/PnX-SI/gn_modulator/tree/develop

Pour la télécharger : https://github.com/PnX-SI/gn_modulator/archive/refs/heads/develop.zip

Ce module étant assez jeune et n'ayant pas encore été utilisé dans d'autres contextes que le projet PASSAGES A FAUNE, nous sommes preneurs de tests et retours dans un autre contexte.

Merci d'avance.

**Comment by marineteneur** [comment]
Bonjour,

Merci pour vos réponses !

Je vais essayer d'installer la version de développement et vous tiendrais au courant des éventuelles avancées.

Bonne journée.
