### ISSUE TITLE
améliorer l'api

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#5]
- [x] params
  - [x] champ `fields` -> liste de champs séparés par une virgule
  - [x] `size` -> `page_size`
  - [x] simplifier filtres (dict -> une seule chaine de caractère à définir ??)

- [x] sorties
  - [x] ajout `next` et `prev` (`has_next`, `has_prev`) 

- [ ] code
  - [x] get one et liste -> faire deux routes
  - [x] export csv et liste -> faire deux routes
  - [ ] utiliser `Flask pagination` https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.Pagination  
  - [ ] optimiser requetes (ne pas toujours demander les column_properties)
    - [x] utilisation de defer pour ne pas demander tous les champs
    - [ ] utilisation de contains_eager pour aviter les n+1

**Comment by amandine-sahl** [comment]
Dans le contexte de la convergence vers monitoring créer des routes pour chaque type d'"objet"

- monitoring/site_group
- monitoring/site
- monitoring/visit
- monitoring/observation

Pour chaque type créer les routes suivantes : 
 - get list
 - get detail
 - insert
 - update
 - delete
 - export => A discuter

**Comment by joelclems** [comment]
Optimisaiton requêtes

route à tester
