### ISSUE TITLE
road to 1.2.0

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#54]
# Prio 1

- [x] Doc sur UUID pouvant être vide mais dont la colonne doit exister
- [x] Doc des champs du fichier d'import - Virer id_digitiser
- [x] Ajouter usages et objectifs de manière simple (sans CD_NOM)
  - [x] Ne pas afficher "Espèces ciblés" dans "Objectifs"  
  - `cor_cd_nom` en base mais caché 
- [x] Ref_Geo - Ajout points
- [x]  Ref_Geo - Ajout table de correspondance entre les couches
- [x] Ajouter commentaires sur PR des tables ref_geo - https://github.com/PnX-SI/RefGeo/pull/12/files
- [x] Doc traitement et intégration BD topo dans Ref_Geo
- [x] Renommer "EXPORT COMPLET", en "EXPORT des PAF"
- [x] Virer onglet Diagnostic de la liste
- [x] Fiches PAF - Inverser long/lat
- [x] Idem dans les exports où lat et long sont inversés il me semble. Sinon on met X et Y dans les exports ? Moi j'aime mieux pour pas s'embrouiller. :)
- [x] Ne plus afficher l'UUID en gros sur les popups fiches
- [x] Virer la modale sur les fiches détails
- [x] Filtres : Ajouter "Spécificités"
- [x] vegetion >> vegetation
- [x] Doc Changelog Maxime
  - [x] insertion / reset ref_geo lineaire points
  - [x] recalcul des intersections 

## serveur demo
- [x] passage 2.13.1
- [x] "Objectifs et usages" manquent les valeurs des listes déroulantes
  - `geonature modulator features m_sipaf.utils` (maj des nomenclatures)
- [x] Caractéristiques > Champs "nomenclature_ouvrage_type". Afficher le label

# En priorité 2 :

-  ~pas de marge pour les diagnostics, medias, titre ?~
- [x] Finaliser import avec relations multiples (acteurs et autre) + DOC
- [x] PR et PK - Ajouter possibilité de les décocher dans le controleur carto
- [x] Ajouter composant carto Nominatim de recherche carto textuelle (existant sur les autres cartes dans GN)
- [x] Quand je clique sur un PAF sur la carte, il ne se met plus en surbrillance dans la liste
- ~Basculer les routes des points dans Ref_geo plutôt que dans Modulator (où on les supprime)~
- [x] Compléter l'export, Répercussion Objectifs et Usages sur Exports et Imports

**Comment by camillemonchicourt** [comment]
La majorité des points ont été inclus dans la 1.2.0.
Reste à voir les priorités 2
