### ISSUE TITLE
Import ajout relation 1-n 

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_modulator#58]
Par exemple pour les acteurs des passages faune
- clés `actors.id_organism`, `actors.id_role`, `actors.id_nomenclature_type_actor`
- [ ] tests
- [ ] donner accès à la liste des organisme (on a besoin du nom exact)
- [ ] supprimer/cacher id_role des acteurs

**Comment by camillemonchicourt** [comment]
Ça serait mieux si ils pouvaient importer avec les noms des organismes, les noms ou codes des rôles. 
Car des ID, ça va être galère pour eux de s'y retrouver et c'est censé être interne et spécifique à la BDD, mais pas pour les imports de données externes.

**Comment by joelclems** [comment]
C'est déjà le cas, on ne manipule pas les id mais bien les noms

**Comment by camillemonchicourt** [comment]
Pourquoi les champs sont nommés ID... alors ?

**Comment by camillemonchicourt** [comment]
Fait dans https://github.com/PnX-SI/gn_modulator/commit/ca49bf87cd9703810a4b14f8fc75c390bb88cdd2

Pour importer un PAF avec plusieurs acteurs, on duplique les lignes du PAF avec un acteur différent à chaque ligne dupliquée.
Pareil pour les usages et autres tables de relations N-N
