### ISSUE TITLE
passages faune fantome lors de la création d'un PF

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/gn_modulator#62]
J'ai créé un passage faune directement sur l'interface en prod (passagesfaune.fr) et après l'édition de la géométrie du PF j'ai de nombreux PF "fantômes" qui apparaissent pas (mais pas dans la synthèse). 
Voici la capture d'écran (en bleu le PF créé et en rond orange apparaissent les ouvrages fantômes : 

![image](https://github.com/PnX-SI/gn_modulator/assets/7148321/68bbe988-7fb1-4a2b-b075-de9dcb2662d1)

**Comment by camillemonchicourt** [comment]
Ce ne sont pas des PAF fantômes mais la couche des PK et PR qui a été ajoutée dans la dernière version et n'est affichée qu'à un certain niveau de zoom.
Ils sont mentionnés dans la légende : 

![image](https://github.com/PnX-SI/gn_modulator/assets/4418840/65a7bcd5-0bb9-4855-9b8c-8b83cab06380)

Vous souhaitez que l'on : 
- Retire cette couche ?
- Ne l'affiche pas par défaut mais seulement si l'utilisateur coche la couche (mais dans ce cas, la plupart des utilisateurs ne verront pas que cette couche est disponible) ?
- Affiche cette couche différemment ?

**Comment by camillemonchicourt** [comment]
Depuis la version 1.3.0, cette couche n'est plus activée par défaut, mais seulement si l'utilisateur l'active.
