### ISSUE TITLE
centrage carte identique entre la consultation des PF et leur création

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/gn_modulator#63]
Lorsqu'on souhaite ajouter un PF, il faut consulter la liste des PF existants sur la carte pour voir s'il existe ou pas. Lorsqu'on clique ensuite sur "nouveau PF" la carte est centrée au centre de la France. Serait il possible de rester sur la même vue carto que lors de la consultation des pF ?

**Comment by camillemonchicourt** [comment]
Oui en effet. On a ce fonctionnement dans Occtax, c'est plus clair.
Quand on créé un relevé, on est sur le même centrage et même zoom que la page précédente.
