### ISSUE TITLE
bug dans l'affichage des passages à faune lors de la création d'un PF

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/gn_modulator#64]
Sur l'interface test, la coche "passages à faune" ou "undefined" qui doit correspondre à la même chose, n'affiche rien (sur cette vue ci dessous il y a déjà eu des pF créés) : 

![image](https://github.com/PnX-SI/gn_modulator/assets/7148321/c7cf3ce7-becc-448a-ad79-33d23b169317)

**Comment by camillemonchicourt** [comment]
Oui c'est un développement en cours à améliorer.

C'est car on a testé de pouvoir afficher la couche des PAF comme couche complémentaires quand on est dans les autres modules, pour pouvoir les localiser quand on est dans la module Occtax ou le module Synthèse.

Mais l'effet de bord est que cette couche additionnelle des PAF s'affiche aussi dans le module SIPAF où elle fait doublon avec la couche PAF du module SIPAF...
