### ISSUE TITLE
passages faune de type polygone invisibles à petite échelle

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/gn_modulator#65]
Les PF ponctuels bénéficient d'un symbole bleu sous forme de cercle dont la taille s'ajuste selon le niveau de zoom. Toutefois pour les PF saisies en tant que polygone, ils deviennent invisibles si l'on dézoom la carte. Ex avec ce PF 375 que je viens de créer, à échelle régionale, il devient invisible. Est il possible d'avoir un symbole permettant de le visualiser à la façon des PF ponctuels ? 

![image](https://github.com/PnX-SI/gn_modulator/assets/7148321/6105ac58-dd11-4bd2-8877-37b04ebb9999)

**Comment by camillemonchicourt** [comment]
C'est souvent le problème avec les polygones...
Une solution est de basculer l'affichage des polygones sous forme de point quand on dézoome.
On a utilisé le plugin https://github.com/oliverroick/Leaflet.Deflate pour ça dans un autre module, mais à voir si c'est une solution fiable et viable.

**Comment by joelclems** [comment]
J'ai utilisé deflate, ça marche plutot bien

**Comment by joelclems** [comment]
soucis avec les popup sur les deflates

**Comment by camillemonchicourt** [comment]
Aperçu ici : 

[Capture vidéo du 20-12-2023 11:16:52.webm](https://github.com/PnX-SI/gn_modulator/assets/4418840/e48f874c-1924-40dc-9942-4750f0689203)

Cela affiche automatiquement les petits polygones et lignes sous forme de points à large échelle et cela bascule automatiquement sur la géométrie précise de l'objet à un certain niveau de zoom.

**Comment by olivier8064** [comment]
Ah c'est parfait comme ça :) bravo

**Comment by joelclems** [comment]
peut être une piste ici pour les tooltip & popup qui ne marche plus avec deflate (seulement pour les polygone et quand on est trop loin, cad visible comme des points)

**Comment by camillemonchicourt** [comment]
Fait dans la version 1.3.0.
