### ISSUE TITLE
Valeur nulle dans les usages impossible après avoir cliqué dessus

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/gn_modulator#66]
Lorsqu'on clique sur l'un des usages et que l'on décide finalement de n'en mettre aucun, cela n'est plus possible, il est indiqué, à tort, que le champs est obligatoire, même si on clique sur la croix pour supprimer la saisie précédente. 
![image](https://github.com/PnX-SI/gn_modulator/assets/7148321/8a0575b5-b32e-4a13-8c07-e4f14dd21519)

**Comment by joelclems** [comment]
la modélisation actuelle est la suivante

le champs `usages` va contenir une liste d'usage.
un usage est constitué
- d'un type d'usage (obligatoire)
- du détail (optionnel)
- d'un commentaire (optionnel)

pour le supprimer il faut cliquer sur la croix à gauche de l'usage

on pourrait peut être le modéliser différemment (et peut être plus simplement) en proposant un champs multiple pour les types d'usage et un même champs détails et commentaire pour tous les usages (directement présent dans la table des passages faune).

**Comment by joelclems** [comment]
oui on peut cacher/désactiver/remetttre à zeo un champs selon la valeur d'autres champs

**Comment by joelclems** [comment]
en cas de passage à faune Spécifique:
- caché pour la page détail
- disabled (grisé et non accessible) pour la page édition / création

**Comment by camillemonchicourt** [comment]
Fait dans la version 1.3.0.
