### ISSUE TITLE
pas de possibilité de supprimer un taxon dans occtax (ou alors c'est peu visible)

### ISSUE THREAD

**Issue by olivier8064** [PnX-SI/gn_modulator#69]
Bonjour, 
Dans occtax en version test, je ne vois pas où supprimer un taxon saisi. Il n' y a que l'icône de modification de la donnée qui apparaît : 

![image](https://github.com/PnX-SI/gn_modulator/assets/7148321/a522ab85-adc1-4289-a8e8-7230486e0179)

**Comment by joelclems** [comment]
Bonjour Olivier, la suppression d'un taxon est possible lorsque l'on a au moins 2 taxons (ou occurrences) enregistrés.

**Comment by olivier8064** [comment]
ah voilà tout s'explique ! merci :) je le préciserai dans la notice

**Comment by camillemonchicourt** [comment]
Ah oui en effet. C'est un sujet lié à GeoNature et son module Occtax, mais c'est vrai que je n'avais fait attention à cela.
C'est normal techniquement, mais en effet, ça peut poser question, même si personne n'a jamais remonté ce sujet jusque là, de mémoire.
